---
- hosts: database
  tasks:
    - name: install mysql
      yum: name=mariadb-server state=present update_cache=yes

    - name: ensure mariadb is started
      service: name=mariadb state=started enabled=yes
