---
- hosts: loadbalancer
  tasks:

    - name: install epel
      yum: name={{ item }} state=present update_cache=yes
      with_items:
        - epel-release
      
    - name: install nginx
      yum: name={{ item }} state=present update_cache=yes
      with_items:
        - nginx

    - name: ensure nginx is started
      service: name=nginx state=started enabled=yes
