---
- hosts: webserver
  become: true
  tasks:
    
    - name: install epel
      yum: name={{ item }} state=present update_cache=yes
      with_items:
        - epel-release

    - name: install web components
      yum: name={{ item }} state=present update_cache=yes
      with_items:
        - httpd
        - mod_wsgi
        - sip
        - python-pip
        - python-virtualenv

    - name: ensure apache is started
      service: name=httpd state=started enabled=yes

    - name: ensure mod_wsgi enabled
      apache2_module: name=wsgi state=present
      notify: restart apache

    - name: copy demo app files
      copy: src=../demo/app/ dest=/var/www/demo mode=0755
      notify: restart apache

    - name: copy virtual host conf
      copy: src=../files/apache-vhost.conf dest=/etc/apache2/sites-available/ mode=0755
      notify: restart apache

  handlers:
    - name: restart apache
      service: name=httpd state=restarted
