---
- hosts: webserver
  become: true
  tasks:
    
    - name: install epel
      yum: name={{ item }} state=present update_cache=yes
      with_items:
        - epel-release

    - name: install web components
      yum: name={{ item }} state=present update_cache=yes
      with_items:
        - httpd
        - mod_wsgi
        - sip
        - python-pip
        - python-virtualenv
