---
- hosts: webserver
  become: true
  tasks:
    
    - name: install epel
      yum: name={{ item }} state=present update_cache=yes
      with_items:
        - epel-release

    - name: install web components
      yum: name={{ item }} state=present update_cache=yes
      with_items:
        - httpd
        - mod_wsgi
        - sip
        - python-pip
        - python-virtualenv

    - name: ensure apache is started
      service: name=httpd state=started enabled=yes

    - name: copy httpd.conf
      copy: src=../files/httpd.conf dest=/etc/httpd/conf/ mode=0755
      notify: restart apache

    - name: copy virtual host conf
      copy: src=../files/apache-vhost.conf dest=/etc/httpd/sites-available/ mode=0755
      notify: restart apache

    - name: create sites-enabled
      file:
        path: /etc/httpd/sites-enabled
        state: directory
        mode: '0755'
      notify: restart apache

    - name: add virtualhost
      file: src=/etc/httpd/sites-available/apache-vhost.conf dest=/etc/httpd/sites-enabled/apache-vhost.conf state=link
      notify: restart apache

    - name: ensure mod_wsgi enabled
      apache2_module: name=wsgi state=present
      notify: restart apache

    - name: copy demo app files
      copy: src=../demo/app/ dest=/var/www/demo mode=0755
      notify: restart apache

    - name: setup virtualenv
      pip: requirements=/var/www/demo/requirements.txt virtualenv=/var/www/demo/.venv
      notify: restart apache

  handlers:
    - name: restart apache
      service: name=httpd state=restarted
